diamonds/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls')),
]

predict/urls.py
from django.urls import path
from . import views

app_name='predict'

urlpatterns = [
    path('', views.indexView, name = 'indexView'),

    path('predictfile/', views.predictfile, name='predictfile'),
]

predict/models.py
from django.db import models

# Create your models here.

predict/views.py
from django.shortcuts import render

from django.shortcuts import render
from django.http import JsonResponse
from sklearn.preprocessing import StandardScaler

from joblib import load
import pandas as pd
import json

model = load('model.joblib')

def indexView(request):
    return render(request, 'index.html')
# Create your views here.
def predictfile(request):
    if request.method == 'POST':
        data = request.POST
        field_example = request.FILES['nameFile']
        df = pd.read_csv(field_example)
        clarity = {'I1':7,'SI2':6,'SI1':5, 'VS2':4, 'VS1':3, 'VVS2':2, 'VVS1':1, 'IF':0}
        color = {'J':6,'I':5,'H':4, 'G':3, 'F':2, 'E':1, 'D':0}
        cut = {'Fair':4,'Good':3,'Very Good':2, 'Premium':1, 'Ideal':0}
        df.clarity.replace(clarity, inplace=True)
        df.color.replace(color, inplace=True)
        df.cut.replace(cut, inplace=True)
        df = df.drop('x', axis=1)
        df = df.drop('y', axis=1)
        df = df.drop('Id', axis=1)
        test_scaled = StandardScaler.fit_transform(df)
        test_scaled = pd.DataFrame(test_scaled,columns=df.columns)


        cat_cols = ['Artist Name', 'Track Name']
        cont_cols =['Popularity','danceability','energy','key','loudness','mode','speechiness','acousticness','instrumentalness','liveness','valence','tempo','duration_in min/ms','time_signature']
        print(test_scaled)
        y_pred = model.predict(test_scaled)
        out = pd.DataFrame(y_pred)
        print(out)
        df['price'] = out
       
        json.dumps(json.loads(df.to_json(orient="records")))


        return JsonResponse(json.dumps(json.loads(df.to_json(orient="records"))),safe=False)

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Hello, world!</title>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="uploaded col-md-12">
            <form method="POST" id="post-form2" enctype="multipart/form-data">
                <div class="input-group mb-3">
                    {% csrf_token %}
                    <input type="file" class="form-control" name="nameFile" id="nameFile">
                    <button class="btn btn-dark" type="submit" id="file">Apply</button>
                </div>
            </form>
        </div>
    </div>
    </div>
    <div class="container pt-5">
      <div class="row">

      <h1>Prediction Results</h1>

          <table class="table" id="records_table">
              <tr>
              <th scope="col">#</th>
              
              <th scope="col">Prediction</th>
              </tr>
             
          </table>
      </div>
  </div>
    <script>
      $("#post-form2").submit(function (e) {
        e.preventDefault();
        var formData = new FormData(this);
        $.ajax({
            url: "{% url 'predict:predictfile' %}",
            type: 'POST',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            
            success: function (response) {
           
              var trHTML = '';
              $.each(JSON.parse(response), function (i, item) {
               
                  trHTML += '<tr><td>' + item.Id + '</td><td>' + item.class + '</td></tr>';
              });
              $('#records_table').append(trHTML);
          },
            error: function (data) {
                console.log("down here")
            }
        });
    });
    </script>

    <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>